services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - saas-network

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
      - NODE_ENV=development
    env_file:
      - ./Backend/.env
    volumes:
      - ./Backend:/app
      - /app/node_modules
    depends_on:
      - redis
    networks:
      - saas-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=300
      - WATCHPACK_POLLING=true
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - saas-network

networks:
  saas-network:
    driver: bridge
